### ISSUE TITLE
Memory usage over 4 times the size of the data set

### ISSUE THREAD

**Issue by Sakkov** [Sakkov/FinGPT#1]
I tried using a training data set of 14.7 GiB and fine tuning data set of 1.1 GiB. The script was able to load all the data into memory but the memory consumption was at times 64 GB (maximum of my computer). It seemed to off load some data from memory while loading the data.

The problem arose when the script started to encode the data. The memory consumption once again climbed to 64 GB and stayed there for a moment before crashing with MemoryError.

```
Traceback (most recent call last):
  File "...\train.py", line 33, in <module>
    model = BigramLanguageModel([preprocessDataPath, fineTuneDataPath])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\bigram.py", line 174, in __init__
    self.content[source_n] = self.encode(self.content[source_n])
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\bigram.py", line 165, in <lambda>
    self.encode = lambda string: [self.stoi[ch] for ch in string]  # encode a string
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\bigram.py", line 165, in <listcomp>
    self.encode = lambda string: [self.stoi[ch] for ch in string]  # encode a string
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
```

**Comment by Sakkov** [comment]
I ran into the same problem with 8.2 GiB training data set with about 7x memory consumption.
